### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by TheTanic** [TheTanic/Semoda#9]
### Description
The application should support different themes. For now it should support a dark and light theme.
### Tasks

- [ ] Define theme colors
- [ ] Create light and dark theme
- [ ] Add option to settings page (see #4)
